In [1]:
# Import the random module.
import random

In [7]:
random.randint(-90,90)

-24

In [8]:
random.Random()

In [16]:
random_number = random.randint(-90,89) + random.random()
random_number

-35.78011881248891

In [13]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [18]:
latitudes

[-17.431849545562446,
 -66.91713156588037,
 60.69316948693895,
 8.063023471846575,
 56.5400729171153,
 -77.10889670164848,
 -19.536504469007568,
 64.35624611846923,
 66.72019617158134,
 -46.39281854572958]

In [22]:
random.randrange(-90,90, step=3)

24

In [23]:
random.randrange(-90,90, step=1)

23

In [24]:
random.uniform(-90,90)

-36.36675649907761

In [25]:
# Import the NumPy module.
import numpy as np

In [26]:
np.random.uniform(-90.000, 90.000)

17.759932216573077

In [27]:
np.random.uniform(-90.000, 90.000, size=50)

array([-33.36600442,   8.41676262,  -9.12446894,  49.15662861,
        75.96136166,   2.52092567,  17.25937209, -17.10503307,
       -83.16401476,  23.51687946,   0.34318218,  -8.3225861 ,
        67.70608205,  55.88960697, -23.28088962,   2.77534735,
       -32.13863311,  85.73455955,  66.16152456, -55.58902695,
       -58.43524775, -14.31176753, -84.74208733, -55.96305826,
        11.38805202, -46.74801811,  70.88361045,   2.5524813 ,
        32.4819999 ,  73.7586292 , -58.70221832,  -3.11307731,
       -68.58205087,  52.57557775, -44.5649265 ,   9.51509749,
       -53.11296673,  85.18117441,  16.42833918,  86.81556538,
       -83.31530567, -40.26210819,  -1.46773747, -53.18949612,
        88.53954099, -19.07511284, -60.18714079, -35.5570316 ,
        42.52801315, -63.36016662])

In [31]:
np.random.uniform(-90.000, 90.000, size=1500)

array([  4.1301844 , -12.85431711,   4.25625617, ..., -62.99181356,
       -69.68417522,  48.27076753])

In [32]:
# Import timeit.
import timeit

In [33]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

14.4 µs ± 265 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

1.47 ms ± 25.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
%timeit latitudes(1500)

1.45 ms ± 23.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [37]:
np.random.uniform(-90.000, 90.000, size=1500)

array([-38.81684299, -88.06924098,  46.17511645, ...,  73.61957833,
        61.46666171, -60.45318035])